# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SMS-Send-NL-MyVodafone
version:      0.01
version_from: lib/SMS/Send/NL/MyVodafone.pm
installdirs:  site
requires:
    SMS::Send:                     0.02
    Test::Simple:                  0.44
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
